projects/urls.py
from django.urls import path

from projects.views import Projects_View, Projects_Add, Projects_Edit, Organizations_Objects_View, \
    Organizations_Objects_Add, Organizations_Objects_Edit, Development_Task_View, Development_Task_Add, \
    Development_Task_Edit, Position_Objects_Edit, Position_Objects_Add, Position_Objects_View, Сabinet_Edit, \
    Сabinet_Add, Сabinet_View, Development_Task_Delete, Development_Task_DetailView, Development_Task_Edit_Date, \
    Development_Task_Edit_Develop, Development_Task_Edit_Status, Position_Objects_DetailView, Position_Objects_Delete, \
    Position_Objects_Edit_Checker, Position_Objects_Upload_Protocol
from projects.views.projects_settings import Organization_Direction_View, Organization_Direction_Add, \
    Organization_Direction_Update, Organization_View, Organization_Add, Organization_Edit, Organization_Detail_View, \
    Type_Document_View, Type_Document_Add, Type_Document_Edit

urlpatterns = [
    path('project/settings/organization_direction/', Organization_Direction_View.as_view(),
         name='organization_direction'),
    path('project/settings/organization_direction/add/', Organization_Direction_Add.as_view(),
         name='organization_direction_add'),
    path('project/settings/organization_direction/edit/<slug:organization_direction_slug>',
         Organization_Direction_Update.as_view(), name='organization_direction_edit'),
    #
    path('project/settings/type_document/', Type_Document_View.as_view(), name='type_document'),
    path('project/settings/type_document/add/', Type_Document_Add.as_view(), name='type_document_add'),
    path('project/settings/type_document/edit/<slug:type_document_slug>', Type_Document_Edit.as_view(),
         name='type_document_edit'),

    path('project/organization/', Organization_View.as_view(), name='organization'),
    path('project/organization/add/', Organization_Add.as_view(), name='organization_add'),
    path('project/organization/edit/<slug:organization_slug>/', Organization_Edit.as_view(),
         name='organization_edit'),
    path('project/organization/view/<slug:organization_slug>/', Organization_Detail_View.as_view(),
         name='organization_detail_view'),

    path('organizations_objects/', Organizations_Objects_View.as_view(), name='organizations_objects'),
    path('organizations_objects/add/', Organizations_Objects_Add.as_view(), name='organizations_objects_add'),
    path('organizations_objects/edit/<slug:organizations_objects_slug>/', Organizations_Objects_Edit.as_view(),
         name='organizations_objects_edit'),

    path('projects/', Projects_View.as_view(), name='projects'),
    path('projects/add/', Projects_Add.as_view(), name='projects_add'),
    path('projects/edit/<slug:project_slug>/', Projects_Edit.as_view(), name='projects_edit'),

    path('development_task/', Development_Task_View.as_view(), name='development_task'),
    path('development_task/add/', Development_Task_Add.as_view(), name='development_task_add'),
    path('development_task/edit/<slug:development_task_slug>/', Development_Task_Edit.as_view(),
         name='development_task_edit'),
    path('development_task/delete/<slug:development_task_slug>/', Development_Task_Delete.as_view(),
         name='development_task_delete'),
    path('development_task/detailed/<slug:development_task_slug>/', Development_Task_DetailView.as_view(),
         name='development_task_detailed'),
    path('development_task/edit/date/<slug:development_task_slug>/', Development_Task_Edit_Date.as_view(),
         name='development_task_edit_date'),
    path('development_task/edit/develop/<slug:development_task_slug>/', Development_Task_Edit_Develop.as_view(),
         name='development_task_edit_develop'),
    path('development_task/edit/status/<slug:development_task_slug>/', Development_Task_Edit_Status.as_view(),
         name='development_task_edit_status'),

    path('position_objects/', Position_Objects_View.as_view(), name='position_objects'),
    path('position_objects/add/', Position_Objects_Add.as_view(), name='position_objects_add'),
    path('position_objects/edit/<slug:position_objects_slug>/', Position_Objects_Edit.as_view(),
         name='position_objects_edit'),
    path('position_objects/detailed/<slug:position_objects_slug>/', Position_Objects_DetailView.as_view(),
         name='position_objects_detailed'),
    path('position_objects/delete/<slug:position_objects_slug>/', Position_Objects_Delete.as_view(),
         name='position_objects_delete'),
    path('position_objects/edit/checker/<slug:position_objects_slug>/', Position_Objects_Edit_Checker.as_view(),
         name='position_objects_edit_checker'),
    path('position_objects/protocol/upload/<slug:position_objects_slug>/', Position_Objects_Upload_Protocol.as_view(),
         name='position_objects_upload_protokol'),

    path('cabinet/', Сabinet_View.as_view(), name='cabinet'),
    path('cabinet/add/', Сabinet_Add.as_view(), name='cabinet_add'),
    path('cabinet/edit/<slug:position_objects_slug>/', Сabinet_Edit.as_view(),
         name='cabinet_edit'),

]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

import workers
from settings import settings
from workers.views import Workers_Login, Workers_Logout, error_noAccess_403

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('workers.urls')),
    path('', include('workers_certificates.urls')),
    path('', include('workers_planning.urls')),
    path('', include('projects.urls')),

    path('login/', Workers_Login.as_view(), name='login'),
    path('logout/', Workers_Logout.as_view(), name='logout'),

]
# обработчик для 404. Страница не найдена
# handler404 = error_pageNotFound_404
# ошибка сервера
# handler500 = error_errorServer_500
# доступ запрещен
handler403 = error_noAccess_403
# невозможно обработать запрос
# handler400 = error_error_400

# Все пользователи
# Страничка одного пользователя
# Добавить нового пользователя
# включаем возможность обработки картинок
# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workers/urls.py
from django.urls import path

from workers.views import Workers, info1, Workers_Views, Workers_Add, Workers_Image, Subdivision_Add, Subdivision_View, \
    Subdivision_Update, Department_Add, Department_View, Department_Update, Chief_Add, Chief_View, Chief_Update, \
    Workers_Change_Password, Workers_Update_Password, Workers_Change, Workers_Basic_Change, Workers_Closed_Change, \
    Workers_Passport, Workers_Signature, Workers_Snils, Workers_Inn, Workers_Archive, Workers_Edit_Сontacts

urlpatterns = [
    path('settings/subdivision/add/', Subdivision_Add.as_view(), name='subdivision_add'),
    path('settings/subdivision/', Subdivision_View.as_view(), name='subdivision'),
    path('settings/subdivision/update/<slug:subdivision_slug>', Subdivision_Update.as_view(),
         name='subdivision_update'),
    path('settings/department/add/', Department_Add.as_view(), name='department_add'),
    path('settings/department/', Department_View.as_view(), name='department'),
    path('settings/department/update/<slug:department_slug>', Department_Update.as_view(),
         name='department_update'),
    path('settings/chief/add/', Chief_Add.as_view(), name='chief_add'),
    path('settings/chief/', Chief_View.as_view(), name='chief'),
    path('settings/chief/update/<slug:chief_slug>', Chief_Update.as_view(), name='chief_update'),

    path('workers/', Workers.as_view(), name='workers'),
    path('workers/views/<slug:workers_slug>', Workers_Views.as_view(), name='workers_views'),
    path('workers/views/image/<slug:workers_slug>', Workers_Image.as_view(), name='workers_image'),
    path('workers/add/', Workers_Add.as_view(), name='workers_add'),
    path('workers/password/change/', Workers_Change_Password.as_view(), name='workers_change_password'),
    path('workers/password/update/<slug:workers_slug>', Workers_Update_Password.as_view(),
         name='workers_update_password'),
    path('workers/update/<slug:workers_slug>', Workers_Change.as_view(), name='workers_update'),
    path('workers/basic/update/<slug:workers_slug>', Workers_Basic_Change.as_view(), name='workers_basic_update'),
    path('workers/closed/update/<slug:workers_slug>', Workers_Closed_Change.as_view(), name='workers_closed_update'),
    path('workers/passport/<slug:workers_slug>', Workers_Passport.as_view(), name='workers_passport'),
    path('workers/snils/<slug:workers_slug>', Workers_Snils.as_view(), name='workers_snils'),
    path('workers/inn/<slug:workers_slug>', Workers_Inn.as_view(), name='workers_inn'),
    path('workers/archive/<slug:workers_slug>', Workers_Archive.as_view(), name='workers_archive'),
    path('workers/signature/<slug:workers_slug>', Workers_Signature.as_view(), name='workers_signature'),
    path('workers/contacts/<slug:workers_slug>', Workers_Edit_Сontacts.as_view(), name='contacts_edit'),

    # path('workers/certificates/', Certificate_Workers.as_view(), name='workers_certificates'),
    # path('workers/certificates/add/', Certificate_Workers_Add_All.as_view(), name='workers_certificate_add_all'),
    # path('workers/certificates/add/<slug:workers_slug>', Certificate_Workers_Add.as_view(), name='workers_certificate_add'),
    #
    # path('settings/certificates/', Сertificates_View.as_view(), name='certificates'),
    # path('settings/certificates/add/', Сertificates_Add.as_view(), name='certificates_add'),
    # path('settings/certificates/update/<slug:сertificates_slug>', Сertificates_Update.as_view(),
    #      name='certificates_update'),
    #
    # path('settings/certificates_parts/', Сertificates_Parts_View.as_view(), name='certificates_parts'),
    # path('settings/certificates_parts/add/', Сertificates_Parts_Add.as_view(), name='certificates_parts_add'),
    # path('settings/certificates_parts/update/<slug:сertificates_parts_slug>', Сertificates_Parts_Update.as_view(),
    #      name='certificates_parts_update'),

    path('', Workers.as_view(), name='base_page')

]

projects/models/projects_settings.py
from django.db import models
from django.urls import reverse
from transliterate import translit
from django.template.defaultfilters import slugify

from workers.models import User, Department


class Organization_Direction(models.Model):
    '''Направление деятельности организации'''
    name = models.CharField(max_length=255, unique=True, verbose_name='Направление дейтельности организации')
    slug = models.SlugField(max_length=100, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Направление дейтельности организации'
        verbose_name_plural = 'Направление дейтельности организаций'
        ordering = ['name']

    def save(self, **kwargs):
        self.slug = slugify(translit(self.name, 'ru', reversed=True))
        super(Organization_Direction, self).save()

    def get_absolute_url(self):
        return reverse('organization_direction_edit', kwargs={'organization_direction_slug': self.slug})


class Organization(models.Model):
    '''Организация'''
    name = models.CharField(max_length=255, unique=True, verbose_name='Организация')
    organization_direction = models.ForeignKey(Organization_Direction, on_delete=models.PROTECT, blank=False, null=True,
                                               verbose_name='Направление деятельности организация')
    site = models.URLField(max_length=255, unique=False, blank=True, verbose_name='Сайт')
    description = models.TextField(verbose_name='Описание фирмы', blank=True)
    slug = models.SlugField(max_length=100, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'
        ordering = ['pk']

    def save(self, **kwargs):
        self.slug = slugify(translit(self.name, 'ru', reversed=True))
        super(Organization, self).save()

    def get_absolute_url(self):
        return reverse('organization_edit', kwargs={'organization_slug': self.slug})


class Type_Document(models.Model):
    '''Типы докуменов разрабатываемых документов'''
    SYSTEM_CHOICES = (
        ('ACS', 'САУ'),
        ('COMPLETELY_ACS', 'Комплектно поставляемые САУ'),
    )
    STAGE_CHOICES = (
        ('WORKING', 'Рабочая'),
        ('OPERATIONAL', 'Эксплуатационная'),
        ('COMPLETELY_ACS', ' - '),
    )
    system = models.CharField(verbose_name='Система', choices=SYSTEM_CHOICES, max_length=100, default='ACS')
    stage = models.CharField(verbose_name='Этап документации', choices=STAGE_CHOICES, max_length=100, default='ACS')
    name = models.CharField(max_length=255, verbose_name='Наименования документа')
    сode_document = models.CharField(max_length=50, blank=True, verbose_name='Код ЭД')
    additional_instructions = models.TextField(verbose_name='Дополнительные указания', blank=True)
    basic_documents = models.BooleanField(default=False, verbose_name='Базовый документ')
    developers = models.ManyToManyField(Department, verbose_name='Отделы')
    sorted = models.IntegerField(default=0, verbose_name='Порядок документов')
    slug = models.SlugField(max_length=100, unique=True, db_index=True,
                            verbose_name='URL')  # unique - Уникальное,db_index - индексируемое

    def __str__(self):
        return self.system + " - " + self.сode_document + " - " + self.name

    def save(self, **kwargs):
        slugSave = self.system + " - " + self.сode_document + " - " + self.name
        self.slug = slugify(translit(slugSave, 'ru', reversed=True))
        super(Type_Document, self).save()

    def get_absolute_url(self):
        return reverse('type_document_edit', kwargs={'type_document_slug': self.slug})

    class Meta:
        verbose_name = 'Разрабатываемый документ'
        verbose_name_plural = 'Разрабатываемые документы'  # Во множественнмо числе
        ordering = ['pk']  # Сортировка по каким полям, - обратная сортировка
        default_permissions = ('')

templates/projects/development_task_edit_date.html
{% extends 'base.html'%}
{% load static %}
{% block style %}
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css'%}">

<link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'%}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'css/adminlte.css'%}">
{% endblock %}
{% block content %}
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{title}} : {{ workers }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'workers'%}">Сотрудники</a></li>

                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">

                 {% if messages %}
                     {% for message in messages %}
                         <div class="text-center alert alert-{{ message.tags }}">
                             {{ message|safe }}
                         </div>
                     {% endfor %}
                 {% endif %}

                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="form-error">{{ forms.non_field_errors }}</div>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="card-body">
                                {% for fr in form%}
                                <div class="form-group">
                                    <label>{{ fr.label }}:</label>
                                    {{ fr }}
                                </div>
                                {% if fr.errors%}
                                <div class="col-md-12">
                                    <div class="card card-danger">
                                        <div class="card-header">
                                            <h3 class="card-title">Ошибка</h3>
                                        </div>
                                        <div class="card-body">
                                            {{ fr.errors }}
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                            <div class="row no-print">
                                <div class="col-12">
                                    <button type="submit" class="btn btn-success float-right">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>


{% endblock %}
{% block script %}

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
<!-- Select2 -->
<script src="{% static 'plugins/select2/js/select2.full.min.js'%}"></script>
<!-- InputMask -->
<script src="{% static 'plugins/moment/moment.min.js'%}"></script>
<script src="{% static 'plugins/moment/moment-with-locales.min.js'%}"></script>

<script src="{% static 'plugins/jQuery-Mask/jquery.mask.js'%}"></script>

<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'%}"></script>

<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2();
    //Date picker
    $('#dateEmployment').datetimepicker({
	    locale: 'ru',
		stepping:10,
		format: 'L',
    });
  })

</script>
{% endblock %}

templates/projects/development_task_edit_status.html
{% extends 'base.html'%}
{% load static %}
{% block style %}
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css'%}">

<link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'%}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'css/adminlte.css'%}">
{% endblock %}
{% block content %}
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{title}} : {{ workers }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'workers'%}">Сотрудники</a></li>

                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">

                 {% if messages %}
                     {% for message in messages %}
                         <div class="text-center alert alert-{{ message.tags }}">
                             {{ message|safe }}
                         </div>
                     {% endfor %}
                 {% endif %}

                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="form-error">{{ forms.non_field_errors }}</div>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="card-body">
                                {% for fr in form%}
                                <div class="form-group">
                                    <label>{{ fr.label }}:</label>
                                    {{ fr }}
                                </div>
                                {% if fr.errors%}
                                <div class="col-md-12">
                                    <div class="card card-danger">
                                        <div class="card-header">
                                            <h3 class="card-title">Ошибка</h3>
                                        </div>
                                        <div class="card-body">
                                            {{ fr.errors }}
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                            <div class="row no-print">
                                <div class="col-12">
                                    <button type="submit" class="btn btn-success float-right">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>


{% endblock %}
{% block script %}

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
<!-- Select2 -->
<script src="{% static 'plugins/select2/js/select2.full.min.js'%}"></script>
<!-- InputMask -->
<script src="{% static 'plugins/moment/moment.min.js'%}"></script>
<script src="{% static 'plugins/moment/moment-with-locales.min.js'%}"></script>

<script src="{% static 'plugins/jQuery-Mask/jquery.mask.js'%}"></script>

<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'%}"></script>

<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2();
    //Date picker
    $('#dateEmployment').datetimepicker({
	    locale: 'ru',
		stepping:10,
		format: 'L',
    });
  })

</script>
{% endblock %}

templates/projects/settings_type_document_view.html
{% extends 'base.html'%}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css'%}">
{% endblock %}
{% block content %}
<!-- Основное поле -->
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <div class="card">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{title}}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Главная</a></li>
                            <li class="breadcrumb-item active">Настройки {{title}}</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="organization-table" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Система</th>
                                        <th>Этап документации</th>
                                        <th>Код ЭД</th>
                                        <th>Наименования документа</th>
                                        <th>Дополнительные указания</th>
                                        <th>Базовый документ</th>
                                        <th>Отделы</th>
                                        {% if perms.workers.change_department or perms.workers.delete_department%}
                                        <th></th>
                                        {%endif%}
                                    </tr>
                                    </thead>
                                    <tbody>{{form}}
                                    {% for type_document in type_documents%}
                                    <tr>
                                        <td>{{type_document.get_system_display}}</td>
                                        <td>{{type_document.get_stage_display}}</td>
                                        <td>{{type_document.сode_document}}</td>
                                        <td>{{type_document.name}}</td>
                                        <td>{{type_document.additional_instructions}}</td>
                                        <td>
                                            {% if type_document.basic_documents%}
                                                Базовый
                                            {%else%}
                                                По согласованию
                                            {%endif%}
                                        </td>
                                        <td>
                                            {%for develop in type_document.developers.all %}
                                            {{develop.abbreviation}}<br>
                                            {%endfor%}
                                        </td>
                                    {% if perms.workers.change_department or perms.workers.delete_department%}
                                        <td width="150px">
                                            {% if perms.workers.change_department %}
                                            <a class="btn btn-info btn-sm" href="{{type_document.get_absolute_url}}"><i
                                                    class="fas fa-pencil-alt"></i> Edit</a>
                                            {%endif%}
                                            {% if perms.workers.delete_department %}
                                            <a class="remove-organization btn btn-danger btn-sm" data-toggle="modal"
                                               data-target="#modal-default" data-slug="{{type_document.slug}}"
                                               data-text="{{type_document.name}}"><i class="fas fa-trash"></i>Delete</a>
                                            {%endif%}
                                        </td>
                                        {%endif%}
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
                {% if perms.workers.add_department %}
                <div class="timeline-footer">
                    <a class="btn btn-success btn-sm float-right" href="{% url 'organization_add' %}">Добавить отдел</a>
                </div>
                {% endif %}
            </div>
            <!-- /.container-fluid -->
            <div class="modal fade" id="modal-default">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Подтверждение операции</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p id="remove-text"></p>
                        </div>
                        <div class="modal-footer justify-content-between">

                            <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                            <a href="" class="btn btn-primary" id="button-remove">Подтвердить</a>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
        </section>
        <!-- /.content -->
        <!-- Основное поле -->
        {% endblock %}
        {% block script %}
        <!-- DataTables  & Plugins -->
        <script src="{% static 'plugins/datatables/jquery.dataTables.min.js'%}"></script>
        <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js'%}"></script>
        <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
        <script>
        $(document).on("click", ".remove-organization", function () {
             var slug = $(this).data('slug');
             var text = $(this).data('text');
             document.getElementById("button-remove").href="?remove="+slug;
             document.getElementById("remove-text").innerText = "Вы пытаетесь удалить : '"+text+"'?";
        });
          $(function () {
            $("#organization-table").DataTable({
              language: {url: '{% static 'plugins/datatables/ru.json'%}'},
              "paging": false,
              "lengthChange": false,
              "searching": true,
              "ordering": true,
              "info": false,
              "autoWidth": false,
              "responsive": true
            }).buttons().container().appendTo('#department-table_wrapper .col-md-6:eq(0)');
          });

        </script>
        {% endblock %}